services:

  php:
    build:
      context: ../container
      dockerfile: Dockerfile
    volumes:
      - ../site:/srv/www
      - /tmp:/tmp
      - node_binaries:/usr/local/node:ro  # Added read-only flag
      - volta_home:/usr/local/volta:ro
    environment:
      - PATH=/usr/local/node/bin:/usr/local/volta/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - VOLTA_HOME=/usr/local/volta
    networks:
      - app-network
    depends_on:
      - node

  nginx:
    image: nginx:1.19.2
    volumes:
      - ../site:/srv/www
      - ./nginx/config/app.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - php

  db:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: test
    ports:
      - "3307:3306"
    volumes:
      - ./db/data:/var/lib/mysql
    networks:
      - app-network

  node:
    build:
      context: ../container/node
      dockerfile: Dockerfile
    volumes:
      - ../site:/srv/www
      - node_binaries:/usr/local/node
      - volta_home:/usr/local/volta
    environment:
      - PATH=/usr/local/node/bin:/usr/local/volta/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - VOLTA_HOME=/usr/local/volta
      - HOST=127.0.0.1
      # This port informs our dev server to listen on port 3000
      - PORT=3000
    network_mode: host
    working_dir: /srv/www/web/app/themes/nynaeve
    tty: true
    stdin_open: true

volumes:
  node_binaries:
  volta_home:

networks:
  app-network:
    driver: bridge


